### ISSUE TITLE
How to delete rows and shift up remaining rows and formatting using openxlsx2

### ISSUE THREAD

**Issue by AomoDa** [JanMarvin/openxlsx2#1003]
Using the `clean_sheet()` method from the package, I am able to clear the data and formatting of the rows, but this method does not remove the rows entirely – it leaves empty rows in their place.

I require a method that would also shift the rows below upwards after deleting the target rows, without losing any formatting or data integrity of the cells below the deleted rows.

**Comment by JanMarvin** [comment]
Hi @AomoDa , this is related to #1001 and I have answered it previously on [Stackoverflow](https://stackoverflow.com/a/75666670/12340029).

The feature you are looking for is obviously interesting from a user perspective, but it has many issues that are not handled by `openxlsx2` and are complicated to implement and therefore I wont do it (unfortunately for you, my reasoning hasn't changed since the Stackoverflow answer). We can do many wonderful things with `openxlsx2`, but deleting or inserting rows/columns is not such a thing.
