### ISSUE TITLE
review exported functions 

### ISSUE THREAD

**Issue by JanMarvin** [JanMarvin/openxlsx2#104]
guess column type must not be exported as well as probably a bunch of other functions. Currently defunct functions should not be exported either.

**Comment by olivroy** [comment]
Before starting removing functions are removing  `@export` tags, you could also add a bunch of `@keywords internal` roxygen tags to functions you don't think should be used, are part of the wanted API.

This will have the benefit of removing these functions from the reference list (decluttering https://janmarvin.github.io/openxlsx2/reference/index.html and in R) while keeping the documentation there in case people are still using them.

Reference
`@keywords` internal which flags the topic as internal and removes from topic indexes. It’s useful because it removes the function from the documentation index; it’s useful for functions aimed primarily at other developers, not typical users of the package.
https://roxygen2.r-lib.org/articles/index-crossref.html#search
