### ISSUE TITLE
`wb_load()` fails when Excel file contains a button

### ISSUE THREAD

**Issue by nicojx** [JanMarvin/openxlsx2#1061]
Hello.

I have an Excel workbook that contains a button, and the file fails to load with `wb_load()`. I can still read data using the `data_only = TRUE` option, but otherwise I get `Error: xml import unsuccessful`.

I attach an attempt at a minimal reproducible example -- it might be too minimal to work out what actually fails, it probably won't open in Excel without complaints. I've deleted quite a lot from the Excel zip container. In any case, the read fails if the file `vmlDrawing1.vml` is present in the folder `xl\Drawings` and succeeds when it's not there. The file is referenced in `\xl\worksheets\sheet2.xlm` (somehow -- it's a copy of the `sheet2.xml` that was causing the problem, but I've deleted most of the content from it).

[test4.zip](https://github.com/user-attachments/files/16021731/test4.zip)

Any help would be appreciated -- I currently have a fair bit of code that deals with this import failing some of the time (when the button is present) and not at others (when the button is not present, as in my use case it's created by VBA).

Thanks!

**Comment by JanMarvin** [comment]
Hi @nicojx , unfortunately this is an issue that we create ourselfs. The file with the button is a `vml` file, which is basically an `xml` file.  Unfortunately a well known spreadsheet software writes incomplete xml in certain cases (a button with a new line) that sometimes looks like this: `a <br> b` which should be something like `a <br/> b`. We replace this, because the original code is not valid xml and wont parse in our xml reader.

In your example above though, the tag is written as `a <br></br> b`. We still replace the `<br>` and create the nonsense `a <br/></br> b`. * sigh*

The issue is here:

https://github.com/JanMarvin/openxlsx2/blob/69252de17c2af08d967f081697103b58b30e162d/R/wb_load.R#L1278

**Comment by JanMarvin** [comment]
Can you give the PR a try?

```R
remotes::install_github("JanMarvin/openxlsx2#1062")
```

**Comment by nicojx** [comment]
I'm afraid I cannot, as I work in a corporate environment, and our RTools installation hasn't been updated to match our R version... I've asked for an update, when it's installed I'll test.

**Comment by JanMarvin** [comment]
No worries, do you know how the button is created? I’d like to have a fully working example file. Is it from excel or libreoffice?

**Comment by JanMarvin** [comment]
It should be fine, I've merged the branch so you should be able to install from r-universe soon. I wasn't able to replicate this using ms365 (always ran into the `a <br> b` condition that we handled previously), latest Libreoffice (does not write the `<br/>` tag at all and also some other unrelated issues) and Numbers (does not handle the button field at all).
