### ISSUE TITLE
Import NA columns

### ISSUE THREAD

**Issue by raffaem** [JanMarvin/openxlsx2#1118]
openxlsx2 is importing empty columns.

This doesn't happen with openxlsx.

MWE:
[test.xlsx](https://github.com/user-attachments/files/16727066/test.xlsx)
```
indf <- openxlsx2::read_xlsx("test.xlsx")
colnames(indf)
```

Output:
```
> colnames(indf)
[1] "project_id" "DUMMY"      NA           NA           NA          
[6] NA           NA           NA           NA 
> dim(indf)
[1] 1001    9
```

The columns are empty:
```
> sum(is.na(indf[,3]))==nrow(indf)
[1] TRUE
```

```
> packageVersion("openxlsx2")
[1] ‘1.8.0.9000’
```

**Comment by JanMarvin** [comment]
Hi @raffaem , thanks for reaching out, but it’s expected that output from `openxlsx` and us differs. You can use arguments to remove empty columns and rows.

**Comment by raffaem** [comment]
I see the `skip_empty_cols` argument.

Shouldn't this be TRUE by default, at the very least?

Why would you want empty columns?

And why is it importing only 7 empty columns and not all the columns the Excel file could contain?

**Comment by JanMarvin** [comment]
@raffaem , we return what is defined in the dimension tag of the xlsx file:

``` r
library(openxlsx2)

# test.xlsx
fl <- "https://github.com/user-attachments/files/16727066/test.xlsx"
wb_load(fl)$worksheets[[1]]$dimension
#> [1] "<dimension ref=\"A1:I1002\"/>"

# openxlsx2_example.xlsx
example_file <- system.file("extdata", "openxlsx2_example.xlsx", package = "openxlsx2")
wb_load(example_file)$worksheets[[1]]$dimension
#> [1] "<dimension ref=\"B2:J12\"/>"
```

In the `test.xlsx` file, the author(s) of said file, created something in the cell dimensions `"A1:I1002"`. And I can see that at least cell `B1002` is part of the first worksheet. Since we do not want to accidentally leave things out or return surprisingly strange results to the user, we simply return the data frame for the cell dimensions `"B2:J1002"`. If that's not desired from the users perspective, we provide arguments to tweak the output.

In my line of work, surprising results are always a cause of concern. If other packages return something else that's fine too. But I cannot (better: do not want to) work with surprises, hence I configured the package as is.

**Comment by raffaem** [comment]
oh ok, that makes a lot of sense
