### ISSUE TITLE
`wb_to_df()` does not find tables but `wb$to_df()` does

### ISSUE THREAD

**Issue by mlell** [JanMarvin/openxlsx2#1159]
Reproducible example is below. `wb_to_df` should not output the error below but should behave the same as the approach where the workbook is first loaded with `wb_load`, right?

``` r
library(openxlsx2) # Commit d359f18af
t <- tempfile(fileext=".xlsx")
wb <- wb_workbook()
wb$add_worksheet("Sheet1")
wb$add_data_table(x = iris, table_name = "test")
wb$save(t)

# Does not work
head(wb_to_df(t, "Sheet1", named_region = "test"))
#> Error in wb_to_df(t, "Sheet1", named_region = "test"): no such named_region

# Works
wb <- wb_load(t)
head(wb$to_df("Sheet1", named_region = "test"))
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#> 2          5.1         3.5          1.4         0.2  setosa
#> 3          4.9         3.0          1.4         0.2  setosa
#> 4          4.7         3.2          1.3         0.2  setosa
#> 5          4.6         3.1          1.5         0.2  setosa
#> 6          5.0         3.6          1.4         0.2  setosa
#> 7          5.4         3.9          1.7         0.4  setosa
```

<sup>Created on 2024-10-10 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by JanMarvin** [comment]
@mlell, thank you for the report, but no need to get huffy. Nobody put bugs in the code to annoy you.
Should be fixed in #1160

**Comment by mlell** [comment]
Dear @JanMarvin , it was not my intention to rant about any of the work you do. Sorry, it seems like I did a bad job writing in English. I am only able to do my work as I do it because of this package and I am grateful and impressed about the improvements you have achieved over the openxlsx package, as well as how quickly you have fixed previous issues.

**Comment by JanMarvin** [comment]
Thanks for the clarification and kind words! (After all this project runs exclusively on kind word).

No harm done. English isn't my first language and therefore I'm very aware that things can get lost in translation. Unfortunately, I've had too many encounters with people acting as if there was an obligation on the part of the developers to fix issues or even develop feature requests. And since you're probably the first one to take a deep dive into all the tables stuff ... Please keep opening issues if things are not working as expected.
