### ISSUE TITLE
Warning message "Found unknown folders in the input file: activeX"

### ISSUE THREAD

**Issue by DataConnection** [JanMarvin/openxlsx2#1202]
Hi,

I get the warning message on opening the attached excel file -  [activeX-element.xlsx](https://github.com/user-attachments/files/18012257/activeX-element.xlsx).
It was generated in Excel - an empty file, with just one activeX element added (in Excel from ribbon "Developer tools").

> file <- openxlsx2::read_xlsx("activeX-element.xlsx") 

>Warning message:
>Found unknown folders in the input file:
>activeX
>...

Probably similar to [https://github.com/JanMarvin/openxlsx2/issues/1012](https://github.com/JanMarvin/openxlsx2/issues/1012)

Thanks for fixing it - no need to hurry - and thanks for your great work!

Wolf

**Comment by JanMarvin** [comment]
Hi @DataConnection ,

thanks for the kind words! I assume you want the activeX element preserved? Unfortunately there is a minor issue here:
<img width="279" alt="Screenshot 2024-12-04 at 19 47 26" src="https://github.com/user-attachments/assets/83438d5a-beb0-436b-8294-176cdabfc6b9">

Could you have a look if #1204 works for you? Since it is unlikely that I ever want to modify the activeX subfolder (or even want to understand its contents), I simply copy the contents from the original file when saving it. If you have access to - please also try if this works with files with more activeX elements.

You can install it like this:
```R
remotes::install_github("JanMarvin/openxlsx2#1204")
```

**Comment by DataConnection** [comment]
Hi @JanMarvin,

thank you very much for your fast reaction and the fix.
I checked #1204, no warning any more on opening the file, the rest works as expected.

Saving with wb_save and reopening in Excel loses some functionality - I get 

```
<recoveryLog xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
<logFileName>error049440_02.xml</logFileName>
<summary>Fehler in Datei 'K:\Test.xlsx'</summary>
<removedRecords>
<removedRecord>Entfernte Datensätze: Objekt von /xl/worksheets/sheet1.xml-Part</removedRecord>
</removedRecords>
</recoveryLog>
``` 
It looks like some properties of activeX elements (i.e. LinkedCell on InputBox) get lost.
But as I need openxlsx2 in this case only for reading, I don't mind. I would also not go in details with the activeX subfolder, I normally do not use them. But if you need any help in testing, feel free to reply. 

Thanks again for your great work, we use openxlsx2 a lot.

Best


Wolf

**Comment by JanMarvin** [comment]
Thanks for the reply! Obviously loading and saving the file correctly is the goal :)
I fixed a thinko. Can you open the file now without complains?

Since I'm not familiar with activeX in spreadsheets, does this work in MS365 on Windows and if yes, how can I reproduce this?

**Comment by DataConnection** [comment]
Yes - now opening the file in Office2021 on Windows works without complains (have no MS365). Great work!

**Comment by JanMarvin** [comment]
Perfect! Thanks for the follow up
