### ISSUE TITLE
Cleanup included files

### ISSUE THREAD

**Issue by JanMarvin** [JanMarvin/openxlsx2#345]
Something that came up with the submission. We might consider removing a few of the included xlsx files and push them to [the data file repo](https://github.com/JanMarvin/openxlsx-data) or exclude them from the package in some other way. There really is no need that we pollute everybody's R library with our files.

Though that might require a bit of rewriting examples and tests.

**Comment by jmbarbone** [comment]
We could maintain them in this repository, exclude them through `.Rbuildignore`, and provide some functions for downloading and retrieval like `wb_download_examples()`, `wb_example_path()`.  We can probably still store them within the `system.file()` location so that when the repo is cloned there's no additional step.  Examples could be safely wrapped with a check for the files.

```r
#' @examples
#' if (file.exists(wb_example_path("test")) {
#'   ...
#' }
```
