### ISSUE TITLE
rowNames=TRUE generates a 1 at top-left of the table

### ISSUE THREAD

**Issue by stla** [JanMarvin/openxlsx2#354]
Hello,

 Thank you for this package. 

I observed that when using `$add_data()` with `rowNames=TRUE`, a `1` is printed in front of the header row:

![openxlsx2](https://user-images.githubusercontent.com/4466543/193400233-643d6e15-cf4d-4f59-a2bd-adefd6971c5e.png)

Cheers.

**Comment by JanMarvin** [comment]
Hi @stla , thanks for the report. I'm aware. That's due to our use of rbind. The same should happen in R when you bind the rownames to a data frame. I never felt like it was an issue, as it can be closed with `add_data(dims = "A1", x = "")` or `remove_data(dims = "A1")` and to me it's unclear what the user expects in said cell.
That been said, I'm all open for suggestions :) 
* Should we create a unique name (aka do nothing)
* Should we add an option to specify a name (SAS price table has a `box` option for this)
* Should the cell be left empty?

**Comment by jmbarbone** [comment]
I think leaving that cell blank is the best option, and returning the `1` seems like a bug.  I don't think it'll be worth it having anything more complicated (like adding a name) that wouldn't be better resolved by adding a new column to the data prior to adding it to the `workbook`.

**Comment by stla** [comment]
I agree. Maybe by doing `names(dat)[1] <- ""` after `cbind(rownames(dat), dat)`.

**Comment by JanMarvin** [comment]
When we do this, we have to think about `add_data_table()`. Iirc table names can not be empty. either we write the row names separately next to the table or use another solution in that case.

**Comment by jmbarbone** [comment]
@JanMarvin , we can probably simplify how `rowNames = TRUE` is implemented and just do a simple `cbind()` before processing:

```r
library(openxlsx2)

df <- data.frame(a = 1:2)

# when `rowNames = TRUE` just append
df2 <- cbind(rownames(df), df)
names(df2)[1] <- ""

wb <- wb_workbook()
wb$add_worksheet()
wb$add_data(x = df, rowNames = TRUE)
wb$add_data(x = df2, startCol = 4)
wb$open()
```

![image](https://user-images.githubusercontent.com/38573843/195469048-9b5e7ff8-df86-41fe-bffc-c5d068c8a3a2.png)
