### ISSUE TITLE
Writing a large dataframe on a preformated worksheet is slow

### ISSUE THREAD

**Issue by D3SL** [JanMarvin/openxlsx2#356]
While testing openxlsx2 I ran into a significant performance difference. In openxlsx writing ~10K rows to a sheet in a preformatted (but blank) workbook is quite quick. It's not instant but pretty close. In openxlsx2 this step takes 2.5-3 minutes. 

Unfortunately I'm not able to share the actual data or workbook but based on my tests I think the issue is the pre-existing formatting and conditional formatting. Creating a new workbook object and dumping 10K or more rows of dummy data is nearly instant, doing the same with the preformatted workbook loaded off disk takes minutes.

**Comment by JanMarvin** [comment]
Hi @D3SL ,

thanks for the report. We are aware of a performance drop when writing large data sets a worksheet with existing cells. Obviously 3 minutes for 10k rows is a bit long, though at the moment improving this is not high on my personal ToDo list and I'll tell you why.

* a) Unlike in `openxlsx` the output file from `openxlsx2` will look identical to the input file. This is due to a "minimal invasive" approach when writing the sheet cell data and its styles.
Unfortunately due to the nature of the xlsx file format we have to check every cell per row and column for information. For instance every cell can provide a certain cell style or be a formula. Visiting many cells is something that is very time consuming. Even the speed of writing 10k rows depends on number of columns. Writing 10k rows and one column should be a lot faster than writing one row and 10k columns.
In addition, we might have other cells on the worksheet we are adding data to. Therefore we have to make sure that we do not alter any of these.

* b) It takes a lot of time to improve such things. This is not to say that it is impossible or that I am entirely happy with the current speed. Faster is always better and I'm sure there are ways to improve what we do, but working on something like this takes a lot of time. Just for reference I have spend literally days improving our write functions. Once I was done, I saw improvements on the milliseconds scale.
First you have to identify the bottlenecks, have to come up with a better solution, implement it, compare the speed, go back to the drawing board (and repeat). Therefore until someone has to constantly deal with this kind of issue, I do not really expect improvements. 
Yet I'm sure that there are still many ways to improve our data writing process (I'm sure that we can save a lot of time, if we could use a more efficient merge process), and if you have an idea and the time to work on it, we'd love to discuss it.

So for now, you could use the 3 minutes as a coffee break, or you create a new worksheet, write the data in that new worksheet, and clone the styles from the pre-formatted sheet.

Oh, and I'm well aware how annoying it is to wait 3 minutes for such a simple task, and I thank you for being an early adapter and hope that you will not be discouraged from using `openxlsx2`.

**Comment by JanMarvin** [comment]
Two ideas to improve the updating speed (writing cells or updating cells of a worksheet with data). In both I assume that the bottleneck is in `update_cell_loop()`:

* We go into `update_cell()`. In this step we create a `cc` dataframe containing all cells of the workbook (pre-exisisting and newly required). It's the entire worksheet data in long format. Once we have this large dataframe, we call `update_cell_loop()` on this dataframe. This works sufficiently well for small to medium dataframes. In your case we create a large dataframe (`cc` will be of length 10k x n, and possibly longer if the sheet contains other cells). Once we enter the `update_cell_loop()` we search for a specific cell to update and update the `cc` dataframe. Ideally, we would limit this dataframe to the cells we are actually going to write/update, presort it in the expected way and update it. Finally, we could join `cc` and all the other cells of the worksheet. That should be significantly faster (not constantly seeking through the entire dataframe).

* We might be able to create a `cc` dataframe similar to the one in `wide_to_long()` (the write function used if no previous `cc` dataframe was found) and merge it with the pre-exisiting `cc` dataframe.

**Comment by JanMarvin** [comment]
Another wasted evening later, maybe there is a fix in #358. This takes the second approach of my last comment. Runs the entire "write data on empty sheet logic". and replaces a few cells in `cc` with this dataframe. Currently this keeps only the cell style. Have to look into `update_cell_loop()` to see if there was something else going on.
