### ISSUE TITLE
text cell to numeric conversion

### ISSUE THREAD

**Issue by JanMarvin** [JanMarvin/openxlsx2#384]
Idea from https://github.com/ycphs/openxlsx/issues/195

We could provide a function that converts a range of cells or a sheet from text to numbers. 

For this to work, we could convert characters to numbers, check for warnings, and if no warning is issued, replace the character contents of the cell with a numeric value.

**Comment by JanMarvin** [comment]
Hi @stees , good question. We haven’t really documented this, but have a look at this.

```r
options(“openxlsx2.string_nums“ = TRUE)

wb <- wb_workbook()$add_worksheet()$add_data(x = data.frame(v1 = as.character(1:5)))
```

this should convert the strings to numerics. Typing on my phone, didn’t check this … is this what you were looking for?

**Comment by stees** [comment]
Actually, I was looking for something more in the lines of `wb_add_numfmt`, but actually converting the cell to "Number".

That's because the input dataframe had to store these columns as character columns, but seeing as Excel allows for cell-specific types, I would like to convert only some of them, after applying other formatting functions (font, fill, etc).

Using `wb_add_numfmt`, I noticed that the number format was indeed inside the properties of the cell, but its type wasn't converted to "Number", so it still returned the same "number stored as text" error.

**Comment by JanMarvin** [comment]
The thing is, strings are stored differently in the openxml format. Numbers are stored as `<v=“1.2”/>` and inline strings as `<is><t>”1.2”</t></is>`. And the number format is just applied to numbers, not to strings.
The option above simply tries to convert every text cell via `as.numeric()` before it is stored in the worksheet.

**Comment by stees** [comment]
Oh, I see. I'll try using that function and binding rows afterwards to see if it works. Thanks.

**Comment by JanMarvin** [comment]
I have added a first draft of a chapter for this to the book: https://janmarvin.github.io/ox2-book/chapters/openxlsx2_number_and_string.html

**Comment by stees** [comment]
`options("openxlsx2.string_nums" = TRUE)` worked great! Is there any way to control the number format after it's converted in this manner?

**Comment by JanMarvin** [comment]
Glad that it works! You should be able to change the number format with `wb_add_numfmt()`, other number formats are not applied when the data is written to the worksheet, because the `wb_add_data()` function still assumes that the cell written was a string and not a number. So if you have mixed columns some manual selection is required.
