### ISSUE TITLE
improve next_sheet() to use unique names

### ISSUE THREAD

**Issue by JanMarvin** [JanMarvin/openxlsx2#480]
This breaks Excel, because two sheets can not have identical names. It's a bit confusing, because as usual the Excel error message is an elaborated version of "something is broken!" Most likely a unique names check should be sufficient and ofc it's a very low impact issue.

``` r
library(openxlsx2)

wb <- wb_workbook()$
  add_worksheet()$
  add_worksheet()$
  remove_worksheet(1)$
  add_worksheet()

wb$get_sheet_names()
#>   Sheet 2   Sheet 2 
#> "Sheet 2" "Sheet 2"
```

**Comment by jmbarbone** [comment]
Can probably resolve it in here:

https://github.com/JanMarvin/openxlsx2/blob/c82866b1858250180c66922383a0338e91e3e3b5/R/class-workbook.R#L386-L392

Should the new worksheet use the first unlisted position (i.e., `"Sheet 1"` again) or would we want a counter so that every time we make a new worksheet it uses that new value (i.e., "Sheet 3")?  I think the latter is how Excel usually works.

**Comment by JanMarvin** [comment]
I guess the latter, because it's simpler and probably what the user expects.

**Comment by JanMarvin** [comment]
I just stumbled over this today, while toying around with #478 and was relieved that for once the bug was not mine :smile:
