### ISSUE TITLE
Some of my half-baked advice

### ISSUE THREAD

**Issue by chuxinyuan** [JanMarvin/openxlsx2#592]
1. Can you change the package name to freexlsx or splxlsx or xlsxverse.
2. It's better to be compatible with openxlsx, or to build on it, than to reinvent the wheel, although I prefer underlining to humps.
3. I would like to have a function comparison table to quickly go from one to the other.

Thanks

**Comment by chuxinyuan** [comment]
@JanMarvin I don't think you should be so rude to my suggestion. Those of you who have studied philosophy know dialectical negation.

**Comment by JanMarvin** [comment]
Hi @chuxinyuan , obviously you have a misunderstanding of how open source development works. This is a bug tracker. Bugs are reported here and feature requests can also be made within reason. You probably discovered this package recently when I [provided a solution to your issue](https://github.com/ycphs/openxlsx/issues/140). And then you opened this thread, which you yourself call "half-baked advice," and were upset when I immediately closed it.

I closed it for several reasons. Because (a) it's not a bug report and you didn't deal with the package and its development, so it's more of a few "showerthoughts", (b) the things mentioned have all been discussed at least a year ago in various places and (c) coming back to the question of how open source development works: we don't need to be told on the internet how to spend our free time developing the projects we provide for free and the issue tracker is not an invitation to ponder that either.

But English is not my native language, nor probably yours, so there are always nuances that get lost in translation. So I didn't mean to be rude, but there is simply no problem here. And on the contrary, I think it is rude to find an open source software project and immediately demand (name) changes from the developers and make desirable but illusory demands about how the software should work please.

But now that we have shared our thoughts on the subject, if you would like to create a more detailed list of how to switch from `openxlsx` to `openxlsx2`, in addition to the existing documentation in the upgrade vignette, feel free to look at the long outdated #34. We always welcome contributions to the package, and as mentioned many times before, documentation is not our strong suit.

**Comment by chuxinyuan** [comment]
@JanMarvin 我还是用母语跟你对话吧！
1. issue >= bug report
2. 你要理解什么是建议，这里仅仅是建议，没有逼着你干什么事的意思，别人给你提建议对于一个有教养的人，难道他不应该虚心接受吗？
3. 回到问题本身。你在输入library(open 的时候系统会自动提示两个包，但是如果你用的包名字是 freexlsx，你输入library(free 的时候，系统会提示你唯一的包，这会带来加载的便利。另外，建立一个全新的世界不好吗？非得从形式上和旧世界保持千丝万缕的关系？你不必回复我，这仅仅是我的建议，你可以选择采纳或不采纳，你也不需要说服我，这是个价值观问题，而不是实证问题。

**Comment by chuxinyuan** [comment]
I probably shouldn't make suggestions casually, because it doesn't affect the specific use, I respect your choice, and thank you for your contribution.
