### ISSUE TITLE
Vignette/documentation comparing with existing solutions?

### ISSUE THREAD

**Issue by wurli** [JanMarvin/openxlsx2#800]
As a frequent user of {openxlsx} I was pleased and intrigued to stumble across this project. However, scanning the README and docs, I wasn't able to find an answer to my main question: 'What does this package do that others don't?'

I, and I'm sure many others, would appreciate a 'Motivation' section in the README, outlining the problems with existing solutions that this package seeks to solve. 

Thanks!

Jacob

**Comment by JanMarvin** [comment]
Thanks for the suggestion @wurli. Currently traveling therefore just a quick answer. Initially it was created to provide a full XML reader that openxlsx was lacking. Since then we've branched out quite a lot. With R6 and many cleanups (better rewrites) and corrections of openxlsx functions along with many new developments such as mschart support and pivot tables just to name a few.

Basically, I was looking for a package that fulfills my needs to load modify and return a identically looking unbroken file and openxlsx and it's could not provide this.

We'll definitely add a section regarding the motivation in one of the vignettes man pages and in the book.

**Comment by wurli** [comment]
Thank you - that’s really helpful to know! Excited to see where this project goes in future 😃

**Comment by JanMarvin** [comment]
You arrived just after the first stable release. The API is stable and you can build production code on the released package. But we still have a few things for upcoming releases on our to-do list and in the development branch. Like file properties and limited xlsb support. Have a look, try things out and tell a friend :)

We have a vignette for upgrading from openxlsx. Maybe start there and let us know how it goes. Open a discussion if you need help or have further questions.

**Comment by JanMarvin** [comment]
Oh and I've said it a couple of times already, I have nothing but love for openxlsx and Phillip was the first I talked to about openxlsx2 and invented him over. Yet, I'd currently consider openxlsx somewhat unmaintained. Phillip has other properties for quite some time now and I lost track of what's going on over there. (It's quite hard to focus on multiple packages, especially because with the XLSX file format you have to check everything against spreadsheet software.) Therefore it might be a good idea either way to switch in case openxlsx gets accidentally archived by CRAN. I believe we provide everything openxlsx had, maybe in different functions, maybe in different ways, but we've been busy the last two years and it paid off.

**Comment by JanMarvin** [comment]
Thanks, added a section to the upgrade vignette
