### ISSUE TITLE
`wb_add_filter()` does not respect value supplied to `cols` argument

### ISSUE THREAD

**Issue by asadow** [JanMarvin/openxlsx2#962]
The below does not work where `cols = c(1, 2, 4, 5)` or the equivalent `which()` statement.

```r
library(openxlsx2)
wb <- wb_workbook()
wb$add_worksheet("Sheet 1")

wb$add_data(1, iris)
wb <- wb_add_filter(wb, 1, rows = 1, cols = which(names(iris) != "Petal.Length"))
wb_open(wb)
```

Strangely the below works (because Sepal.Length is the first column?).

```r
library(openxlsx2)
wb <- wb_workbook()
wb$add_worksheet("Sheet 1")

wb$add_data(1, iris)
wb <- wb_add_filter(wb, 1, rows = 1, cols = which(names(iris) != "Sepal.Length"))
wb_open(wb)
```

**Comment by olivroy** [comment]
I think this is a limitation of Excel itself. 

In a sheet, a filter can only be applied to a single region.

In your code, don't forget to do the assignment if you work with functions starting with `wb_add_*()`.

(I edited your example to be functional.

**Comment by JanMarvin** [comment]
Hi @asadow , like @olivroy says a filter can only be applied to a consecutive cell region. Interestingly `wb_add_filter()` is a function where we’re missing a dims argument.

Unfortunately it is not possible to customize a filter using selected columns or rows. See https://github.com/JanMarvin/openxlsx2/issues/129 for ideas how to create a custom auto filter. But this issue never left the ideas stage, because one has to hide the rows manually, which made the entire idea very much non trivial and potentially quite error prone

**Comment by JanMarvin** [comment]
Precisely. Maybe one day in the future we will be able to set custom auto filters, but for now that’s a  manual task left to the user.
